<?xml version="1.0" encoding="windows-1252"?>
<!DOCTYPE QXDocument [
<!ELEMENT QXDocument (Header, Page*)>
<!ELEMENT Header (Title*, DocType*, Creator*, Author*, Date*, Copyright*, Orientation*)>
<!ELEMENT DocType (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Creator (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Copyright (#PCDATA)>
<!ELEMENT Orientation (#PCDATA)>
<!ELEMENT Page (Item*)>
<!ELEMENT Item (#PCDATA)>
<!ELEMENT Contents (#PCDATA)>
<!ATTLIST Header Units CDATA "mm">
<!ATTLIST Header Pagewidth CDATA "210">
<!ATTLIST Header Pageheight CDATA "297">
<!ATTLIST Header PaperName CDATA "A4">
<!ATTLIST Header Layers CDATA "3">
<!ATTLIST Item Type CDATA "Text">
<!ATTLIST Item XPos CDATA "0">
<!ATTLIST Item YPos CDATA "0">
<!ATTLIST Item Font CDATA "Arial">
<!ATTLIST Item Height CDATA "12">
<!ATTLIST Item Color CDATA "Black">
<!ATTLIST Item BackColor CDATA "White">
<!ATTLIST Item Weight CDATA "Normal">
<!ATTLIST Item Decoration CDATA "None">
<!ATTLIST Item Width CDATA "1">
<!ATTLIST Item Height CDATA "1">
<!ATTLIST Item Shape CDATA "0">
<!ATTLIST Item ControlID CDATA "">
<!-- 0=rect, 1=ellipse, 2=hline,3=vline,4=roundrect-->
<!ATTLIST Item Linewidth CDATA "1">
<!ATTLIST Item FillType CDATA "0">
<!ATTLIST Item Layer CDATA "0">
<!ATTLIST Item Opacity CDATA "1">
<!ATTLIST Item ImageFile CDATA "">
<!ATTLIST Item Compression CDATA "None">
<!ATTLIST Item Xscale CDATA "1.0">
<!ATTLIST Item Yscale CDATA "1.0">
<!ATTLIST Item Extra CDATA "">
<!ATTLIST Page Number CDATA "1">
]>
<QXDocument>
<Header Pagewidth="215,90" Pageheight="279,40" PaperName="A4" Units="mm">
   <Title></Title>
   <DocType></DocType>
   <Creator>QRXDocumentFilter</Creator>
   <Author></Author>
   <Date>05/09/2016</Date>
   <Copyright></Copyright>
   <Orientation>Portrait</Orientation>
</Header>
<Page Number="1">
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="6,88" Linewidth="0,26" Shape="0" Width="202,94" Height="31,75" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="93,66" YPos="10,18" Height="16" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">LIVRO RAZÃO</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="15,12" YPos="23,67" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Nome</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="15,12" YPos="27,11" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">CNPJ</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="24,38" YPos="23,67" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">AGBR COMERCIO SERVIÇOS GRAFICOS IMPORTAÇÃO E EXPORTAÇÃO LTDA</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="24,38" YPos="27,11" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">11.416.247/0001-00</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="15,12" YPos="33,99" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Folha</Item>
<Item Type="Graphic" Layer="1" XPos="14,55" YPos="37,31" Linewidth="0,53" Shape="2" Width="192,88" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="QRShape2">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="22,79" YPos="23,67" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">:</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="22,79" YPos="27,11" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">:</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="22,79" YPos="33,99" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">:</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="24,38" YPos="33,99" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="15,12" YPos="30,55" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Data</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="24,38" YPos="30,55" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">01/01/2013 a 31/12/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="22,79" YPos="30,55" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">:</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="111,13" YPos="17,58" Height="8" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="38,89" Linewidth="0,26" Shape="0" Width="202,94" Height="24,61" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="46,21" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Conta :</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="23,32" YPos="46,21" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">1.1.1.1.01.0001</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="60,36" YPos="46,21" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Sequência :</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="73,59" YPos="46,21" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">17</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="98,72" YPos="46,21" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Descrição :</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="111,16" YPos="46,21" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">CAIXA</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="18,26" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Data</Item>
<Item Type="Graphic" Layer="1" XPos="14,55" YPos="58,47" Linewidth="0,53" Shape="2" Width="12,44" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_data">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="28,57" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Lançamento</Item>
<Item Type="Graphic" Layer="1" XPos="28,31" YPos="58,47" Linewidth="0,53" Shape="2" Width="13,23" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_documento">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="48,42" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Contra-Partida</Item>
<Item Type="Graphic" Layer="1" XPos="42,86" YPos="58,47" Linewidth="0,53" Shape="2" Width="26,99" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_contra_partida">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="100,01" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Histórico</Item>
<Item Type="Graphic" Layer="1" XPos="71,17" YPos="58,47" Linewidth="0,53" Shape="2" Width="66,41" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_historico">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="141,29" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Valor de Débito</Item>
<Item Type="Graphic" Layer="1" XPos="138,91" YPos="58,47" Linewidth="0,53" Shape="2" Width="21,96" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_debito">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="164,31" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Valor de Crédito</Item>
<Item Type="Graphic" Layer="1" XPos="162,19" YPos="58,47" Linewidth="0,53" Shape="2" Width="21,96" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_credito">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="193,68" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Saldo</Item>
<Item Type="Graphic" Layer="1" XPos="185,47" YPos="58,47" Linewidth="0,53" Shape="2" Width="21,96" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_saldo">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="195,53" YPos="59,70" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">8.282,12</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="14,59" YPos="59,70" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">Anterior</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="59,70" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="63,50" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">01/01/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="36,25" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4638</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="151,34" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">5.573,52</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="194,20" YPos="63,93" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">13.855,64</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.2.01.0002</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF AJUSTE SALDO ANO ANTERIOR DEZEMBRO </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="66,84" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">DE 2012</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="63,93" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">3599)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="70,38" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">02/01/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">186</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="151,34" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.000,00</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="194,20" YPos="70,83" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">14.855,64</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.2.01.0003</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF SAQUE CH 153 - SUPRIMENTO DE CAIXA</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="70,83" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4022)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="74,35" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="74,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">03/01/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="74,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">428</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="160,87" YPos="74,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="178,06" YPos="74,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">42,00</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="194,20" YPos="74,83" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">14.813,64</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="74,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4.2.1.0.01.0005</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="74,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF CUPOM FISCAL Nº 6383 - SOLIRIA DA SILVA </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="77,74" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">GONÇALVES PENA EPP</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="74,83" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="74,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">2356)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="74,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="81,23" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="81,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">03/01/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="81,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">429</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="160,87" YPos="81,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="178,06" YPos="81,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">24,00</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="194,20" YPos="81,73" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">14.789,64</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="81,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4.2.1.0.01.0033</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="81,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF CUPOM FISCAL Nº 11327 - REI DOS </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="84,64" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">PARAFUSOS LTDA ME</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="81,73" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="81,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4916)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="81,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="88,11" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="88,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">03/01/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="88,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">430</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="160,87" YPos="88,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="176,74" YPos="88,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">136,40</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="194,20" YPos="88,63" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">14.653,24</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="88,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">2.1.1.1.01.0012</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="88,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF PGTO VALE TRANSPORTE ADRIANA </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="91,54" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">CRISTINA DIAS</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="88,63" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="88,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4374)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="88,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="94,99" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="95,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">04/01/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="95,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">425</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="160,87" YPos="95,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="178,06" YPos="95,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">20,00</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="194,20" YPos="95,53" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">14.633,24</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="95,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4.2.1.0.01.0033</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="95,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF PG COM NOTA FISCAL Nº 995 - LAVA JATO </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="98,44" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">BAN BAN LTDA ME</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="95,53" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="95,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4916)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="95,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="101,86" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="102,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">04/01/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="102,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">426</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="160,87" YPos="102,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="178,06" YPos="102,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">19,80</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="194,20" YPos="102,43" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">14.613,44</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="102,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4.2.1.0.01.0028</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="102,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF CUPOM FISCAL Nº 89445 - HOLLYWOOD </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="105,34" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">PRODUTOS ALIMENTICIOS LTDA EPP</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="102,43" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="102,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4879)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="102,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="108,74" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="109,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">04/01/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="109,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">427</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="160,87" YPos="109,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="178,06" YPos="109,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">33,99</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="194,20" YPos="109,33" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">14.579,45</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="109,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4.2.1.0.01.0005</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="109,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF PG COM NOTA FISCAL Nº 16089 - JAG </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="112,24" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">UTILIDADES LTDA ME</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="109,33" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="109,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">2356)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="109,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="115,62" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="116,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">05/01/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="36,25" YPos="116,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">5995</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="160,87" YPos="116,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="173,30" YPos="116,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">17.500,00</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="193,94" YPos="116,23" Height="7" Color="#FF0000" Weight="Bold" Decoration="none" ControlID =" ">(2.920,55)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="116,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4.2.1.1.01.0002</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="116,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF PAGAMENTO DE SALARIO DO MES 01/2013</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="116,23" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">C</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="116,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">2424)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="116,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="119,59" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="120,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">06/01/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="120,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">194</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="151,34" YPos="120,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.000,00</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="120,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="193,94" YPos="120,23" Height="7" Color="#FF0000" Weight="Bold" Decoration="none" ControlID =" ">(1.920,55)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="120,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.2.01.0003</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="120,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF SAQUE BANCO DE BRASILIA P/ CAIXA</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="120,23" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">C</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="120,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4022)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="120,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="123,83" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="124,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">07/01/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="124,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">420</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="160,87" YPos="124,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="176,74" YPos="124,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">147,45</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="193,94" YPos="124,23" Height="7" Color="#FF0000" Weight="Bold" Decoration="none" ControlID =" ">(2.068,00)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="124,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4.2.1.0.01.0028</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="124,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF CUPOM FISCAL Nº 15445 - CASE CUL ATAC </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="127,14" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">E IND PROD IND SA</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="124,23" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">C</Item>