<?xml version="1.0" encoding="windows-1252"?>
<!DOCTYPE QXDocument [
<!ELEMENT QXDocument (Header, Page*)>
<!ELEMENT Header (Title*, DocType*, Creator*, Author*, Date*, Copyright*, Orientation*)>
<!ELEMENT DocType (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Creator (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Copyright (#PCDATA)>
<!ELEMENT Orientation (#PCDATA)>
<!ELEMENT Page (Item*)>
<!ELEMENT Item (#PCDATA)>
<!ELEMENT Contents (#PCDATA)>
<!ATTLIST Header Units CDATA "mm">
<!ATTLIST Header Pagewidth CDATA "210">
<!ATTLIST Header Pageheight CDATA "297">
<!ATTLIST Header PaperName CDATA "A4">
<!ATTLIST Header Layers CDATA "3">
<!ATTLIST Item Type CDATA "Text">
<!ATTLIST Item XPos CDATA "0">
<!ATTLIST Item YPos CDATA "0">
<!ATTLIST Item Font CDATA "Arial">
<!ATTLIST Item Height CDATA "12">
<!ATTLIST Item Color CDATA "Black">
<!ATTLIST Item BackColor CDATA "White">
<!ATTLIST Item Weight CDATA "Normal">
<!ATTLIST Item Decoration CDATA "None">
<!ATTLIST Item Width CDATA "1">
<!ATTLIST Item Height CDATA "1">
<!ATTLIST Item Shape CDATA "0">
<!ATTLIST Item ControlID CDATA "">
<!-- 0=rect, 1=ellipse, 2=hline,3=vline,4=roundrect-->
<!ATTLIST Item Linewidth CDATA "1">
<!ATTLIST Item FillType CDATA "0">
<!ATTLIST Item Layer CDATA "0">
<!ATTLIST Item Opacity CDATA "1">
<!ATTLIST Item ImageFile CDATA "">
<!ATTLIST Item Compression CDATA "None">
<!ATTLIST Item Xscale CDATA "1.0">
<!ATTLIST Item Yscale CDATA "1.0">
<!ATTLIST Item Extra CDATA "">
<!ATTLIST Page Number CDATA "1">
]>
<QXDocument>
<Header Pagewidth="215,90" Pageheight="279,40" PaperName="A4" Units="mm">
   <Title></Title>
   <DocType></DocType>
   <Creator>QRXDocumentFilter</Creator>
   <Author></Author>
   <Date>05/09/2016</Date>
   <Copyright></Copyright>
   <Orientation>Portrait</Orientation>
</Header>
<Page Number="1">
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="6,88" Linewidth="0,26" Shape="0" Width="202,94" Height="31,75" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="93,66" YPos="10,18" Height="16" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">LIVRO RAZÃO</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="15,12" YPos="23,67" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Nome</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="15,12" YPos="27,11" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">CNPJ</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="24,38" YPos="23,67" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">AGBR COMERCIO SERVIÇOS GRAFICOS IMPORTAÇÃO E EXPORTAÇÃO LTDA</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="24,38" YPos="27,11" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">11.416.247/0001-00</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="15,12" YPos="33,99" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Folha</Item>
<Item Type="Graphic" Layer="1" XPos="14,55" YPos="37,31" Linewidth="0,53" Shape="2" Width="192,88" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="QRShape2">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="22,79" YPos="23,67" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">:</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="22,79" YPos="27,11" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">:</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="22,79" YPos="33,99" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">:</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="24,38" YPos="33,99" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="15,12" YPos="30,55" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Data</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="24,38" YPos="30,55" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">01/01/2013 a 31/12/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="22,79" YPos="30,55" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">:</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="111,13" YPos="17,58" Height="8" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="38,89" Linewidth="0,26" Shape="0" Width="202,94" Height="24,61" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="46,21" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Conta :</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="23,32" YPos="46,21" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">1.1.4.4.04.0004</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="60,36" YPos="46,21" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Sequência :</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="73,59" YPos="46,21" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">8174</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="98,72" YPos="46,21" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Descrição :</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="111,16" YPos="46,21" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">FERNANDO ANTONIO SANTOS OLIVIERI</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="18,26" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Data</Item>
<Item Type="Graphic" Layer="1" XPos="14,55" YPos="58,47" Linewidth="0,53" Shape="2" Width="12,44" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_data">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="28,57" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Lançamento</Item>
<Item Type="Graphic" Layer="1" XPos="28,31" YPos="58,47" Linewidth="0,53" Shape="2" Width="13,23" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_documento">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="48,42" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Contra-Partida</Item>
<Item Type="Graphic" Layer="1" XPos="42,86" YPos="58,47" Linewidth="0,53" Shape="2" Width="26,99" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_contra_partida">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="100,01" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Histórico</Item>
<Item Type="Graphic" Layer="1" XPos="71,17" YPos="58,47" Linewidth="0,53" Shape="2" Width="66,41" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_historico">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="141,29" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Valor de Débito</Item>
<Item Type="Graphic" Layer="1" XPos="138,91" YPos="58,47" Linewidth="0,53" Shape="2" Width="21,96" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_debito">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="164,31" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Valor de Crédito</Item>
<Item Type="Graphic" Layer="1" XPos="162,19" YPos="58,47" Linewidth="0,53" Shape="2" Width="21,96" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_credito">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="193,68" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Saldo</Item>
<Item Type="Graphic" Layer="1" XPos="185,47" YPos="58,47" Linewidth="0,53" Shape="2" Width="21,96" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_saldo">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="192,88" YPos="59,70" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">222.452,76</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="14,59" YPos="59,70" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">Anterior</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="59,70" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="63,50" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">01/01/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">354</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="150,02" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">16.068,04</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="192,88" YPos="63,93" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">238.520,80</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">2.1.1.1.01.0009</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF APROPRIAÇÃO DE NF 99837 MB SET </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="66,84" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">INDUSTRIAL LTDA  (COMPRA DE PLASTICO) ESTE </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="69,75" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">MATERIAL FOI LEVADO POR FERNANDO ANTONIO </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="72,66" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">SANTOS OLIVIERI </Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="63,93" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4343)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="76,20" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="76,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">01/01/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="76,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">525</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="151,34" YPos="76,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">3.716,31</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="76,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="192,88" YPos="76,63" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">242.237,11</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="76,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">2.1.1.1.01.0010</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="76,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF APROPRIAÇÃO DE NF 9060 - CELIMAR IND </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="79,54" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">COM DE PLASTICOS LTDA (COMPRA DE MATERIAL) </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="82,45" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">SR FERNANDO ANTONIO SANTOS OLIVIERI LEVOU </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="85,36" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">CONSIGO ESTE MATERIAL </Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="76,63" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="76,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4350)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="76,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="88,90" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="89,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">09/01/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="89,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">372</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="151,34" YPos="89,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4.448,67</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="89,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="192,88" YPos="89,33" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">246.685,78</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="89,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.2.01.0003</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="89,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF PAGAMENTO COM CH Nº 232 - NEWLAND </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="92,24" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VEICULOS LTDA PARCELA 02/24  PARA O SOCIO </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="95,15" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">FERNANDO ANTONIO SANTOS OLIVIERI</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="89,33" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="89,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4022)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="89,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="98,69" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="99,13" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">09/01/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="99,13" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">385</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="153,46" YPos="99,13" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">852,43</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="99,13" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="192,88" YPos="99,13" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">247.538,21</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="99,13" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.2.01.0003</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="99,13" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF PAGAMENTO COM CH Nº 232 - ENERGIA </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="102,04" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">ELETRICA - CEB LOTE 04/06-FERNANDO ANTONIO </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="104,95" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">SANTOS OLIVIERI</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="99,13" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="99,13" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4022)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="99,13" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="108,48" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="108,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">20/02/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="108,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">538</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="151,34" YPos="108,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.013,96</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="108,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="192,88" YPos="108,93" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">248.552,17</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="108,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.2.01.0003</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="108,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF DEBITO EM CONTA CONF. FATURA </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="111,84" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">ENERGIA ELETRICA - CEB LOTE 04/06 -FERNANDO </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="114,75" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">ANTONIO SANTOS OLIVIERI</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="108,93" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="108,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4022)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="108,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="118,27" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="118,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">20/02/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="118,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">547</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="151,34" YPos="118,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4.448,67</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="118,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="192,88" YPos="118,73" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">253.000,84</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="118,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="118,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF DEBITO EM CONTA CONF. PGTO DE </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="121,64" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">PARCELA 03/20 NEWLAND VEICULOS LTDA  PARA O </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="124,55" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">SOCIO FERNANDO ANTONIO SANTOS OLIVIERI</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="118,73" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="69,85" YPos="118,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="118,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="128,06" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="128,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">20/02/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="128,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">547</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="153,46" YPos="128,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">513,07</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="128,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="192,88" YPos="128,53" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">253.513,91</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="128,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="128,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF DEBITO EM CONTA CONF. PGTO PARCELA </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="131,44" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">03/20 NEWLAND VEICULOS LTDA - JUROS</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="128,53" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="69,85" YPos="128,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="128,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="134,94" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="135,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">01/03/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="135,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">962</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="153,46" YPos="135,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">876,53</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="135,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="192,88" YPos="135,43" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">254.390,44</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="135,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.2.01.0003</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="135,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">PGTO DE ENERGIA ELETRICA REF.02/2013 - LOTE </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="138,34" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">04/06</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="135,43" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="135,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4022)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="135,43" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="141,82" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="142,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">05/03/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="36,25" YPos="142,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">5146</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="150,02" YPos="142,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">19.102,74</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="142,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="192,88" YPos="142,33" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">273.493,18</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="142,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.1.01.0001</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="142,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF PG COM NOTA FISCAL Nº 106066 MB SET </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="145,24" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">INDUSTRIAL TDA (COMPRA DE MATERIAL) FOI </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="148,15" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">ENTRE AO SR FERNANDO ANTONIO SANTOS </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="151,06" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">OLIVIERI</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="142,33" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="66,41" YPos="142,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">17)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="142,33" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="154,52" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="155,03" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">06/03/2013</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="155,03" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">829</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="151,34" YPos="155,03" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4.448,67</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="155,03" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="192,88" YPos="155,03" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">277.941,85</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="155,03" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>