<?xml version="1.0" encoding="windows-1252"?>
<!DOCTYPE QXDocument [
<!ELEMENT QXDocument (Header, Page*)>
<!ELEMENT Header (Title*, DocType*, Creator*, Author*, Date*, Copyright*, Orientation*)>
<!ELEMENT DocType (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Creator (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Copyright (#PCDATA)>
<!ELEMENT Orientation (#PCDATA)>
<!ELEMENT Page (Item*)>
<!ELEMENT Item (#PCDATA)>
<!ELEMENT Contents (#PCDATA)>
<!ATTLIST Header Units CDATA "mm">
<!ATTLIST Header Pagewidth CDATA "210">
<!ATTLIST Header Pageheight CDATA "297">
<!ATTLIST Header PaperName CDATA "A4">
<!ATTLIST Header Layers CDATA "3">
<!ATTLIST Item Type CDATA "Text">
<!ATTLIST Item XPos CDATA "0">
<!ATTLIST Item YPos CDATA "0">
<!ATTLIST Item Font CDATA "Arial">
<!ATTLIST Item Height CDATA "12">
<!ATTLIST Item Color CDATA "Black">
<!ATTLIST Item BackColor CDATA "White">
<!ATTLIST Item Weight CDATA "Normal">
<!ATTLIST Item Decoration CDATA "None">
<!ATTLIST Item Width CDATA "1">
<!ATTLIST Item Height CDATA "1">
<!ATTLIST Item Shape CDATA "0">
<!ATTLIST Item ControlID CDATA "">
<!-- 0=rect, 1=ellipse, 2=hline,3=vline,4=roundrect-->
<!ATTLIST Item Linewidth CDATA "1">
<!ATTLIST Item FillType CDATA "0">
<!ATTLIST Item Layer CDATA "0">
<!ATTLIST Item Opacity CDATA "1">
<!ATTLIST Item ImageFile CDATA "">
<!ATTLIST Item Compression CDATA "None">
<!ATTLIST Item Xscale CDATA "1.0">
<!ATTLIST Item Yscale CDATA "1.0">
<!ATTLIST Item Extra CDATA "">
<!ATTLIST Page Number CDATA "1">
]>
<QXDocument>
<Header Pagewidth="215,90" Pageheight="279,40" PaperName="A4" Units="mm">
   <Title></Title>
   <DocType></DocType>
   <Creator>QRXDocumentFilter</Creator>
   <Author></Author>
   <Date>05/09/2016</Date>
   <Copyright></Copyright>
   <Orientation>Portrait</Orientation>
</Header>
<Page Number="1">
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="6,88" Linewidth="0,26" Shape="0" Width="202,94" Height="31,75" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="93,66" YPos="10,18" Height="16" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">LIVRO RAZÃO</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="15,12" YPos="23,67" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Nome</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="15,12" YPos="27,11" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">CNPJ</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="24,38" YPos="23,67" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">AGBR COMERCIO SERVIÇOS GRAFICOS IMPORTAÇÃO E EXPORTAÇÃO LTDA</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="24,38" YPos="27,11" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">11.416.247/0001-00</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="15,12" YPos="33,99" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Folha</Item>
<Item Type="Graphic" Layer="1" XPos="14,55" YPos="37,31" Linewidth="0,53" Shape="2" Width="192,88" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="QRShape2">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="22,79" YPos="23,67" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">:</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="22,79" YPos="27,11" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">:</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="22,79" YPos="33,99" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">:</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="24,38" YPos="33,99" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="15,12" YPos="30,55" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Data</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="24,38" YPos="30,55" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">01/01/2012 a 31/12/2012</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="22,79" YPos="30,55" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">:</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="111,13" YPos="17,58" Height="8" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="38,89" Linewidth="0,26" Shape="0" Width="202,94" Height="24,61" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="46,21" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Conta :</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="23,32" YPos="46,21" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">1.1.4.4.04.0001</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="60,36" YPos="46,21" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Sequência :</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="73,59" YPos="46,21" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">8143</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="98,72" YPos="46,21" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Descrição :</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="111,16" YPos="46,21" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">FREDERICO JOSE N. S. MEDEIROS</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="18,26" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Data</Item>
<Item Type="Graphic" Layer="1" XPos="14,55" YPos="58,47" Linewidth="0,53" Shape="2" Width="12,44" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_data">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="28,57" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Lançamento</Item>
<Item Type="Graphic" Layer="1" XPos="28,31" YPos="58,47" Linewidth="0,53" Shape="2" Width="13,23" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_documento">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="48,42" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Contra-Partida</Item>
<Item Type="Graphic" Layer="1" XPos="42,86" YPos="58,47" Linewidth="0,53" Shape="2" Width="26,99" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_contra_partida">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="100,01" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Histórico</Item>
<Item Type="Graphic" Layer="1" XPos="71,17" YPos="58,47" Linewidth="0,53" Shape="2" Width="66,41" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_historico">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="141,29" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Valor de Débito</Item>
<Item Type="Graphic" Layer="1" XPos="138,91" YPos="58,47" Linewidth="0,53" Shape="2" Width="21,96" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_debito">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="164,31" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Valor de Crédito</Item>
<Item Type="Graphic" Layer="1" XPos="162,19" YPos="58,47" Linewidth="0,53" Shape="2" Width="21,96" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_credito">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="193,68" YPos="54,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">Saldo</Item>
<Item Type="Graphic" Layer="1" XPos="185,47" YPos="58,47" Linewidth="0,53" Shape="2" Width="21,96" Height="1,06" Color="#000000" BackColor="#FFFFFF" FillType="Outline" ControlID="shape_saldo">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="192,88" YPos="59,70" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">122.121,52</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="14,59" YPos="59,70" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">Anterior</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="59,70" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="63,50" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">01/01/2012</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="36,25" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">6363</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="160,87" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="173,30" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">22.940,14</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="194,20" YPos="63,93" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">99.181,38</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">4.2.1.1.01.0002</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF PAGAMENTO DE ABONO/PARTICIPAÇÃO </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="66,84" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">NOS LUCROS MESES 07/2011 ATÉ 12/2011</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="63,93" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">2424)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="63,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="70,38" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">03/01/2012</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="36,25" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1061</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="156,10" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">5,00</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="194,20" YPos="70,83" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">99.186,38</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.1.01.0001</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF RETIRADA DE SOCIO FREDERICO JOSE N. </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="73,74" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">DA SILVA MEDEIROS - ESTACIONAMENTO</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="70,83" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="66,41" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">17)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="70,83" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="77,26" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="77,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">03/01/2012</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="36,25" YPos="77,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1791</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="154,78" YPos="77,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">87,20</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="77,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="194,20" YPos="77,73" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">99.273,58</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="77,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.1.01.0001</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="77,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF RETIRADA DE SOCIO FREDERICO JOSE N. </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="80,64" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">DA SILVA MEDEIROS - RGB RESTAURANTES LTDA</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="77,73" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="66,41" YPos="77,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">17)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="77,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="84,14" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="84,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">03/01/2012</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="36,25" YPos="84,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">5810</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="153,46" YPos="84,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">100,00</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="84,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="194,20" YPos="84,63" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">99.373,58</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="84,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="84,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF PAGAMENTO COM CUPOM FISCAL Nº 17462 </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="87,54" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">NESTLE BRASIL LTDA -PARTE</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="84,63" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="69,85" YPos="84,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="84,63" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="91,02" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="91,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">05/01/2012</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="91,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">717</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="154,78" YPos="91,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">97,65</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="91,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="194,20" YPos="91,53" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">99.471,23</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="91,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.2.01.0002</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="91,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF RETIRADA DE SOCIO FREDERICO JOSE N. </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="94,44" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">DA SILVA MEDEIROS - PAGAMENTO DE FATURA </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="97,35" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">AMERICAN EXPRESS BUSINESS ( UNIDAS SÃO </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="100,26" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">PAULO LOCADORA)</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="91,53" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="91,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">3599)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="91,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="103,72" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="104,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">05/01/2012</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="104,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">718</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="153,46" YPos="104,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">300,00</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="104,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="194,20" YPos="104,23" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">99.771,23</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="104,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.2.01.0002</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="104,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF RETIRADA DE SOCIO FREDERICO JOSE N. </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="107,14" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">DA SILVA MEDEIROS - CONDOMINIO EDIFICIO </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="110,05" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">CORAL</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="104,23" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="63,76" YPos="104,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">3599)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="104,23" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="113,51" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="114,03" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">05/01/2012</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="114,03" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">845</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="153,46" YPos="114,03" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">186,50</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="114,03" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="194,20" YPos="114,03" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">99.957,73</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="114,03" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.2.01.0001</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="114,03" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF RETIRADA DE SOCIO FREDERICO JOSE N. </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="116,94" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">DA SILVA MEDEIROS - VITORIA SA</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="114,03" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="66,41" YPos="114,03" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">24)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="114,03" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="120,39" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="120,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">05/01/2012</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="120,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">846</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="154,78" YPos="120,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">89,32</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="120,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="192,88" YPos="120,93" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">100.047,05</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="120,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.2.01.0001</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="120,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF RETIRADA DE SOCIO FREDERICO JOSE N. </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="123,84" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">DA SILVA MEDEIROS - CIA BRASILEIRA DE </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="126,75" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">DISTRIBUIÇÃO</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="120,93" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="66,41" YPos="120,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">24)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="120,93" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="130,18" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="130,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">05/01/2012</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="36,25" YPos="130,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1069</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="154,78" YPos="130,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">19,65</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="130,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="192,88" YPos="130,73" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">100.066,70</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="130,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.1.01.0001</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="130,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF RETIRADA DE SOCIO FREDERICO JOSE N. </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="133,64" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">DA SILVA MEDEIROS - SUDOESTE COMERCIAL DE </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="136,55" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">ALIMENTOS</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="130,73" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="66,41" YPos="130,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">17)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="130,73" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>
<Item Type="Graphic" Layer="2" XPos="12,96" YPos="139,96" Linewidth="0,26" Shape="0" Width="202,94" Height="3,97" Color="#000000" BackColor="#FFFFFF" FillType="Fill" ControlID="">Graphic item</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="14,59" YPos="140,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">06/01/2012</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="37,57" YPos="140,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">847</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="151,34" YPos="140,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.244,00</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="184,15" YPos="140,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" "></Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="192,88" YPos="140,53" Height="7" Color="#000000" Weight="Bold" Decoration="none" ControlID =" ">101.310,70</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="42,90" YPos="140,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">1.1.1.2.01.0001</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="140,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">VLR REF RETIRADA DE SOCIO FREDERICO JOSE N. </Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="71,21" YPos="143,44" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">DA SILVA MEDEIROS - TRANS ADRIANA CASTILHO</Item>
<Item Type="Text" Layer="0" Font="Arial" XPos="205,58" YPos="140,53" Height="7" Color="#080000" Weight="Bold" Decoration="none" ControlID =" ">D</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="66,41" YPos="140,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">24)</Item>
<Item Type="Text" Layer="0" Font="Tahoma" XPos="61,42" YPos="140,53" Height="7" Color="#080000" Weight="normal" Decoration="none" ControlID =" ">(</Item>